### ISSUE TITLE
Timeout decorator is no longer working with python 3.8

### ISSUE THREAD

**Issue by vacary** [siconos/faf#8]
Timeout decorator is no longer working with python 3.8. It seems that there is an issue with the name of the function from
`Caller._internal_call` to ` __main__.Caller._internal_call`

It is perhaps related to `if __name__ == '__main__':`

```
Traceback (most recent call last):
  File "/Users/acary/Work/faf/src/comp.py", line 221, in __call__
    self._internal_call(solver, sproblem, filename, pfilename,
  File "/Users/acary/Work/faf/src/faf_timeout.py", line 40, in inner
    proc.start()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function Caller._internal_call at 0x1120e6f70>: it's not the same object as __main__.Caller._internal_call
```

**Comment by vacary** [comment]
Another example that seems related
https://stackoverflow.com/questions/50079165/multiprocessing-picklingerror-in-python-3-6-5-that-doesnt-occur-in-3-6-1/50079674#50079674

**Comment by vacary** [comment]
it works in python 3.7 :-(

**Comment by vacary** [comment]
Answer seems to be 
https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/

**Comment by vacary** [comment]
Temporary fix in 888da8453b964f4c1360fcdcbe4be351119ba397
